[package]
name = "ls"
version = "0.1.0"
authors = ["Yishu See <yishuyishu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
colored = "1.9"
libc = "0.2"
structopt = "0.3"
